apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-demo.baseName" . }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.nginxDemo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-demo.labels" . | nindent 4 }}
  type: {{ .Values.nginxDemo.service.type }}
